### ISSUE TITLE
Allow for custom wtfpl pages

### ISSUE THREAD

**Issue by redchair123** [TehShrike/wtfpl2.com#1]
look to https://github.com/remy/mit-license for guidance.

http://mit-license.org/

http://rem.mit-license.org/

**Comment by TehShrike** [comment]
I wonder what the easiest way would be to do this programmatically.  Use Github Pages and make a wtfpl Github organization where each custom variation gets its own repo maybe?

**Comment by TehShrike** [comment]
Actually, that mit license page expects people to host gh-page forks under their own names, doesn't it.  That does sound easier.

**Comment by TehShrike** [comment]
There is a gh-pages branch that is now the default, people can fork it to make their own versions
